<a href="https://colab.research.google.com/github/jasonyang26b/RStudio/blob/main/F_Test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
library(tidyverse)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.6
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.1     ✔ tibble    3.3.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.2
✔ purrr     1.2.1
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [3]:
d <- data.frame(
  x_1 = runif(1000), # random draw from uniform distribution
  x_2 = runif(1000),
  x_3 = runif(1000),
  x_4 = runif(1000)) %>%
    mutate(
    y = -1 + 1 * x_1 + 2 * x_2 + 0 * x_3 + 0 * x_4 + rnorm(1000)
    )

In [5]:
head(d)

  x_1       x_2       x_3       x_4       y
1 0.6811315 0.7954222 0.5834999 0.4395952 -0.01474536
2 0.8170370 0.6338094 0.2860354 0.1793215  3.02945663
3 0.2194571 0.8507612 0.7611064 0.9246733  2.15480092
4 0.1190281 0.3838625 0.5898828 0.5947859  2.03849531
5 0.6824159 0.4232022 0.8699142 0.2317336  1.18178708
6 0.2574346 0.7943896 0.9258397 0.2515331  0.81371195

In [7]:
model_short <- lm(y ~ 1, data = d)
model_long_a <- lm(y ~ 1 + x_1 + x_2, data = d)
model_long_b <- lm( y ~ 1 + x_1 + x_2 + x_3 + x_4, data = d)

In [8]:
model_short

Call:
lm(formula = y ~ 1, data = d)

Coefficients:
(Intercept)
     0.5265

In [9]:
model_long_a

Call:
lm(formula = y ~ 1 + x_1 + x_2, data = d)

Coefficients:
(Intercept)          x_1          x_2
     -0.967        0.930        1.982

In [10]:
anova(model_long_a, model_short, test='F')

  Res.Df RSS       Df Sum of Sq F        Pr(>F)
1 997     999.8845 NA        NA       NA           NA
2 999    1380.5650 -2 -380.6804 189.7911 1.434366e-70

In [11]:
anova(model_long_b, model_short, test='F')

  Res.Df RSS       Df Sum of Sq F        Pr(>F)
1 995     997.2585 NA        NA       NA          NA
2 999    1380.5650 -4 -383.3064 95.60958 7.44724e-69

In [12]:
anova(model_long_b, model_long_a, test='F')

  Res.Df RSS      Df Sum of Sq F       Pr(>F)
1 995    997.2585 NA        NA      NA        NA
2 997    999.8845 -2 -2.625988 1.31002 0.2702795