<a href="https://colab.research.google.com/github/jasonyang26b/R/blob/main/F_Test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
install.packages('sandwich')
install.packages('lmtest')

library(tidyverse)
library(sandwich)
library(lmtest)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

also installing the dependency ‘zoo’


Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.6
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.1     ✔ tibble    3.3.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.2
✔ purrr     1.2.1
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
Loading required package: zoo


Attaching package: ‘zoo’


The following objects are masked from ‘package:base’:

    as.Date, as.Date.numeric

In [2]:
d <- data.frame(
  x_1 = runif(1000), # random draw from uniform distribution
  x_2 = runif(1000),
  x_3 = runif(1000),
  x_4 = runif(1000)) %>%
    mutate(
    y = -1 + 1 * x_1 + 2 * x_2 + 0 * x_3 + 0 * x_4 + rnorm(1000)
    )

In [3]:
head(d)

  x_1       x_2       x_3       x_4        y
1 0.8079078 0.1885229 0.1673223 0.72450999  1.3047812
2 0.4201824 0.1370730 0.7414345 0.02328317 -0.2701459
3 0.8835766 0.6328132 0.8736536 0.45581779  1.4953142
4 0.2117041 0.0487449 0.4254456 0.75703195  0.4560711
5 0.5781939 0.3435085 0.8040449 0.37349790 -0.3803405
6 0.2848567 0.7260187 0.5424096 0.34561976  1.3117589

In [4]:
model_short <- lm(y ~ 1, data = d)
model_long_a <- lm(y ~ 1 + x_1 + x_2, data = d)
model_long_b <- lm( y ~ 1 + x_1 + x_2 + x_3 + x_4, data = d)

In [5]:
model_short

Call:
lm(formula = y ~ 1, data = d)

Coefficients:
(Intercept)
      0.458

In [6]:
model_long_a

Call:
lm(formula = y ~ 1 + x_1 + x_2, data = d)

Coefficients:
(Intercept)          x_1          x_2
    -0.9859       0.9434       1.9794

In [7]:
anova(model_long_a, model_short, test='F')

  Res.Df RSS      Df Sum of Sq F        Pr(>F)
1 997    1066.362 NA        NA       NA           NA
2 999    1487.500 -2 -421.1382 196.8725 8.722915e-73

In [8]:
anova(model_long_b, model_short, test='F')

  Res.Df RSS      Df Sum of Sq F        Pr(>F)
1 995    1057.815 NA        NA       NA           NA
2 999    1487.500 -4 -429.6857 101.0426 3.212693e-72

In [9]:
anova(model_long_b, model_long_a, test='F')

  Res.Df RSS      Df Sum of Sq F        Pr(>F)
1 995    1057.815 NA        NA       NA         NA
2 997    1066.362 -2 -8.547544 4.019989 0.01824554

In [11]:
coeftest(model_short, vcovHC(model_short))
# coeftest: from 'lmtest', hypothesis tests for regression coefficients.
# by default, it reports:
  # coefficient estimate
  # standard error
  # t_statistic
  # p-value

# vcovHC() from 'sandwich', a heteroskedasticity-consistent (robust) variance-covariance matrix.
# instead of classical SE, it uses the robust sandwich estimator.

t test of coefficients:

            Estimate Std. Error t value  Pr(>|t|)
(Intercept) 0.457965   0.038607  11.862 < 2.2e-16 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1