<a href="https://colab.research.google.com/github/jasonyang26b/R/blob/main/F_Test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
install.packages('sandwich')
install.packages('lmtest')

library(tidyverse)
library(sandwich)
library(lmtest)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

also installing the dependency ‘zoo’


Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.6
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.1     ✔ tibble    3.3.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.2
✔ purrr     1.2.1
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
Loading required package: zoo


Attaching package: ‘zoo’


The following objects are masked from ‘package:base’:

    as.Date, as.Date.numeric

In [2]:
d <- data.frame(
  x_1 = runif(1000), # random draw from uniform distribution
  x_2 = runif(1000),
  x_3 = runif(1000),
  x_4 = runif(1000)) %>%
    mutate(
    y = -1 + 1 * x_1 + 2 * x_2 + 0 * x_3 + 0 * x_4 + rnorm(1000)
    )

In [ ]:
head(d)

  x_1        x_2       x_3       x_4        y
1 0.75185925 0.3628142 0.7514082 0.72507860  0.6950631
2 0.11311548 0.6102358 0.4315732 0.97761101  0.6865459
3 0.97209749 0.8098031 0.4645696 0.89029177  1.3677434
4 0.18887206 0.5349060 0.9878451 0.73775602  0.8449473
5 0.19446484 0.5730908 0.8647041 0.83599466  0.9192629
6 0.01930491 0.1265549 0.4110717 0.06634159 -0.6688886

In [ ]:
model_short <- lm(y ~ 1, data = d)
model_long_a <- lm(y ~ 1 + x_1 + x_2, data = d)
model_long_b <- lm( y ~ 1 + x_1 + x_2 + x_3 + x_4, data = d)

In [ ]:
model_short

Call:
lm(formula = y ~ 1, data = d)

Coefficients:
(Intercept)
      0.471

In [ ]:
model_long_a

Call:
lm(formula = y ~ 1 + x_1 + x_2, data = d)

Coefficients:
(Intercept)          x_1          x_2
    -1.0046       0.9917       1.9622

In [ ]:
anova(model_long_a, model_short, test='F')

  Res.Df RSS      Df Sum of Sq F        Pr(>F)
1 997    1007.314 NA        NA       NA           NA
2 999    1395.595 -2 -388.2813 192.1529 2.600536e-71

In [ ]:
anova(model_long_b, model_short, test='F')

  Res.Df RSS      Df Sum of Sq F        Pr(>F)
1 995    1003.738 NA        NA       NA           NA
2 999    1395.595 -4 -391.8569 97.11139 8.641882e-70

In [ ]:
anova(model_long_b, model_long_a, test='F')

  Res.Df RSS      Df Sum of Sq F        Pr(>F)
1 995    1003.738 NA        NA       NA        NA
2 997    1007.314 -2 -3.575616 1.772244 0.1704872

In [ ]:
coeftest(model_short, vcovHC(model_short))

t test of coefficients:

            Estimate Std. Error t value  Pr(>|t|)
(Intercept) 0.470995   0.037395  12.595 < 2.2e-16 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1